### ISSUE TITLE
Payment Slip (BVR/ESR) - Problems with output methodes - memory and disk

### ISSUE THREAD

**Issue by mncoon** [OCA/l10n-switzerland#122]
## Module:

Switzerland - Payment Slip (BVR/ESR)
## Steps to recreate:
- tested on a test-database with test-data
- also tested with a clone of a customer-database
## Errors:

Merge Slips in Memory:
If Payment Slip is created from Invoice, the PDF is empty.

Merge Slips on Disk:
It raises the following error:
`Traceback (most recent call last):
  File "/opt/odoo/addons/report/controllers/main.py", line 121, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/opt/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/report/controllers/main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/l10n_ch_payment_slip/report/payment_slip_from_invoice.py", line 68, in get_pdf
    context=context
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/l10n_ch_payment_slip/report/payment_slip_from_invoice.py", line 58, in _generate_one_slip_per_page_from_invoice_pdf
    return self.merge_pdf_on_disk(docs)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/l10n_ch_payment_slip/report/reports_common.py", line 89, in merge_pdf_on_disk
    buff.close()
UnboundLocalError: local variable 'buff' referenced before assignment`

**Comment by philhug** [comment]
I can reproduce the problem. It might be related to the error I receive when trying to manually create a BVR reference number:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 935, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 927, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5123, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3121, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3167, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5550, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 817, in **get**
    self.determine_value(record)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 919, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 875, in compute_value
    self._compute_value(records)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 867, in _compute_value
    self.compute(records)
  File "/var/lib/odoo/addons/8.0/l10n_ch_payment_slip/payment_slip.py", line 663, in draw_payment_slip_image
    img = self._draw_payment_slip()
  File "/var/lib/odoo/addons/8.0/l10n_ch_payment_slip/payment_slip.py", line 616, in _draw_payment_slip
    initial_position, company)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/var/lib/odoo/addons/8.0/l10n_ch_payment_slip/payment_slip.py", line 423, in _draw_address
    draw.text((x, y), com_partner.name, font=font, fill=self._fill_color)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 267, in text
    mask, offset = font.getmask2(text, self.fontmode)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 160, in getmask2
    size, offset = self.font.getsize(text)
TypeError: expected string

**Comment by nbessi** [comment]
@copmn can you give me details about your OS, hardware, python version and wkhtml2pdf command

**Comment by mncoon** [comment]
@nbessi I quickly tried to recreate this. 

To answer your question:

```
OS: Debian 7
Hardware: VMWare Virtual Server 1GB Memory, 1 CPU, 8GB Disk
Python: 2.7.3 (default, Mar 13 2014, 11:03:55
wkhtmltopdf: 0.12.1 (with patched qt)
```

I also tested again.
Merge in Memory: PDF is empty

Merge on Disk: receive this messages:

![screenshot-192 168 222 212 8069 2015-07-24 17-20-01](https://cloud.githubusercontent.com/assets/7815772/8877879/4984efa6-3228-11e5-95be-71abaa554498.png)

```
2015-07-24 17:09:56,803 2687 ERROR cofair_bvr_test openerp.service.report: Exception: local variable 'buff' referenced before assignment
Traceback (most recent call last):
  File "/opt/odoo/server/openerp/service/report.py", line 93, in go
    result, format = openerp.report.render_report(cr, uid, ids, object, datas, context)
  File "/opt/odoo/server/openerp/report/__init__.py", line 40, in render_report
    return registry['ir.actions.report.xml'].render_report(cr, uid, ids, name, data, context)
  File "/opt/odoo/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons-extra/l10n_ch_payment_slip/report/ir_action.py", line 74, in render_report
    context=context
  File "/opt/odoo/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/server/openerp/addons/base/ir/ir_actions.py", line 153, in render_report
    return self.pool['report'].get_pdf(cr, uid, res_ids, new_report, data=data, context=context), 'pdf'
  File "/opt/odoo/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons-extra/l10n_ch_payment_slip/report/payment_slip_from_invoice.py", line 73, in get_pdf
    report_name=report_name,
  File "/opt/odoo/server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons-extra/l10n_ch_payment_slip/report/payment_slip_from_invoice.py", line 63, in _generate_one_slip_per_page_from_invoice_pdf
    return self.merge_pdf_on_disk(pdfs)
  File "/opt/odoo/addons-extra/l10n_ch_payment_slip/report/reports_common.py", line 83, in merge_pdf_on_disk
    buff.close()
UnboundLocalError: local variable 'buff' referenced before assignment
```

```
Traceback (most recent call last):
  File "/opt/odoo/server/addons/web/controllers/main.py", line 69, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 1564, in index
    request.session.db, request.session.uid, request.session.password, report_id)
  File "/opt/odoo/server/openerp/http.py", line 872, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/server/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/server/openerp/service/report.py", line 34, in dispatch
    res = fn(db, uid, *params)
  File "/opt/odoo/server/openerp/service/report.py", line 141, in exp_report_get
    return _check_report(report_id)
  File "/opt/odoo/server/openerp/service/report.py", line 119, in _check_report
    raise openerp.osv.orm.except_orm(exc.message, exc.traceback)
except_orm: (u"local variable 'buff' referenced before assignment", (<type 'exceptions.UnboundLocalError'>, UnboundLocalError("local variable 'buff' referenced before assignment",), <traceback object at 0x6fc9ea8>))
```

```

Traceback (most recent call last):
  File "/usr/share/pyshared/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/share/pyshared/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/server/openerp/service/server.py", line 281, in app
    return self.app(e, s)
  File "/opt/odoo/server/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/server/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/server/openerp/http.py", line 1280, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/server/openerp/http.py", line 1254, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/share/pyshared/werkzeug/wsgi.py", line 411, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/server/openerp/http.py", line 1421, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/server/addons/crm/ir_http.py", line 13, in _dispatch
    response = super(ir_http, self)._dispatch()
  File "/opt/odoo/server/addons/website/models/ir_http.py", line 145, in _dispatch
    resp = super(ir_http, self)._dispatch()
  File "/opt/odoo/server/openerp/addons/base/ir/ir_http.py", line 176, in _dispatch
    return self._handle_exception(e)
  File "/opt/odoo/server/addons/website/models/ir_http.py", line 193, in _handle_exception
    return super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/server/openerp/addons/base/ir/ir_http.py", line 146, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/server/openerp/http.py", line 659, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/openerp/addons/base/ir/ir_http.py", line 172, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/server/openerp/http.py", line 677, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server/openerp/http.py", line 404, in response_wrap
    response = response.get_response()
TypeError: get_response() takes exactly 2 arguments (1 given)
```

Hope this helps a little bit.

**Comment by yvaucher** [comment]
buff is defined here in for loop:

https://github.com/OCA/l10n-switzerland/blob/8.0/l10n_ch_payment_slip/report/reports_common.py#L70

Thus if there is not doc to loop on it will fail. In the try except which will try to close it.

I think buff should be declared outside of the loop.

**Comment by yvaucher** [comment]
This won't fix the empty report but it will fix the stack trace:

https://github.com/OCA/l10n-switzerland/pull/158

**Comment by yvaucher** [comment]
@copmn In version 9.0 I added few error messages to help the user do his settings.
I'll close this issue I close this as #158 has been merged
