### ISSUE TITLE
l10n_ch_dta How is this working in Odoo 8

### ISSUE THREAD

**Issue by diezcode** [OCA/l10n-switzerland#177]
l10n_ch_dta How is this working in Odoo 8? Where to find dta

**Comment by yvaucher** [comment]
You should have an option "Create DTA" in `More` menu in form view of Payment Order

You will also see it in view list of Accounting -> Payments -> Payment Order if you select at least one payment

**Comment by diezcode** [comment]
When I try to create a dta this error comes:

Traceback (most recent call last):
  File "/opt/odoo/src/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/src/openerp/http.py", line 526, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/src/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/src/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/src/openerp/http.py", line 282, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/src/openerp/http.py", line 742, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/src/openerp/http.py", line 378, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/src/openerp/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/src/openerp/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/src/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/src/openerp/api.py", line 360, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/customer_addons/l10n_ch_dta/wizard/create_dta.py", line 775, in create_dta
    dta_file = self._create_dta(data)
  File "/opt/odoo/src/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/customer_addons/l10n_ch_dta/wizard/create_dta.py", line 705, in _create_dta
    elec_context, seq
  File "/opt/odoo/src/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/customer_addons/l10n_ch_dta/wizard/create_dta.py", line 668, in _process_payment_lines
    pline.bank_id.get_account_number() or
  File "/opt/odoo/src/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/src/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
TypeError: get_account_number() takes at least 4 arguments (4 given)

**Comment by yvaucher** [comment]
I think you are missing the fix done in this commit:
https://github.com/OCA/l10n-switzerland/commit/2dc682a3b51cb5ea0953a06f131216c3662edd45

Please update your module by downloading the last version, restarting your server and update it on your instance.

get_account_number needs to have a @api.multi decorator instead of @api.model

As it seems your code is outdated, I close this issue
