### ISSUE TITLE
Error when installing l10n_ch_payment_slip_layouts

### ISSUE THREAD

**Issue by diezcode** [OCA/l10n-switzerland#183]
File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 1393, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ParseError: "Wrong value for ir.actions.report.xml.report_type: 'reportlab-pdf'" while parsing /opt/custom_addons/l10n_ch_payment_slip_layouts/report/report.xml:10, near
<report id="invoice_and_one_slip_per_page_from_invoice" model="account.invoice" string="Invoice with Payment Slip" report_type="reportlab-pdf" name="invoice_and_one_slip_per_page_from_invoice"/>

How to clear this ?

**Comment by yvaucher** [comment]
@diezcode For which version of Odoo ? 8.0 ?

**Comment by diezcode** [comment]
@yvaucher  yes 8.0
Can someone fix this or what is the problem? =)

**Comment by diezcode** [comment]
hello??? @guewen any help? this module is not working on ODOO v8

**Comment by yvaucher** [comment]
@diezcode Sorry I have no time yet to check this. Could you provide the full stack trace to be able to investigate?

**Comment by diezcode** [comment]
@yvaucher Yes here you have all the stack:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/usr/lib/python2.7/dist-packages/openerp/tools/convert.py", line 360, in _tag_report
    id = self.pool['ir.model.data']._update(cr, self.uid, "ir.actions.report.xml", self.module, res, xml_id, noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 1069, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/custom_addons/report_aeroo/report_xml.py", line 560, in create
    res_id = super(report_xml, self).create(vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/magento_addons/connector/producer.py", line 48, in create
    record_id = create_original(self, vals)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4041, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 4161, in _create
    self._check_selection_field_value(cr, user, field, vals[field], context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 2256, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 1323, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ParseError: "Wrong value for ir.actions.report.xml.report_type: 'reportlab-pdf'" while parsing /home/test/custom_addons/l10n_ch_payment_slip_layouts/report/report.xml:10, near
<report id="invoice_and_one_slip_per_page_from_invoice" model="account.invoice" string="Invoice with Payment Slip" report_type="reportlab-pdf" name="invoice_and_one_slip_per_page_from_invoice"/>

**Comment by diezcode** [comment]
any fix? @yvaucher

**Comment by lepistone** [comment]
Hi @diezcode, as I'm sure you know, this is an open source project, so people might have the time to help, but you can't expect that.

I didn't investigate your problem, but if you found a solution and would be willing to share it, that would be great!

Thanks for reporting!

**Comment by yvaucher** [comment]
@diezcode Have you the last version of the module l10n_ch_payment_slip ? On runbot I don't have this error.

It seems that in your case the following code isn't working or maybe not present:
https://github.com/OCA/l10n-switzerland/blob/8.0/l10n_ch_payment_slip/report/ir_action.py#L29-L36

Please make sure you have the last version of the module and you might want to delete your .pyc files to ensure the executed code is the right one.

**Comment by diezcode** [comment]
It's working fine now. My Problem was, that I had an old l10n_ch_payment_slip modul. Now  with the new one its ok. Another question. It is possible to add this with the aeroo report Templates?
Thanks for your help.

**Comment by lepistone** [comment]
I'm closing this, thanks! aeroo is OT on this ticket (in general, there are no aeroo reports in OCA branches as far as I know, but you can of course make your own reports).
