### ISSUE TITLE
[7.0] Error when trying to print ESR/BVR

### ISSUE THREAD

**Issue by bodi000** [OCA/l10n-switzerland#360]
Hello,

I installed the l10n_ch_payment_slip module needed to generate ESRs. While trying to print, I get a recurring error in the logs. Any idea why?
I know the focus is not on v7 anymore, but I would like to use this module...

Thank you in advance.
B
```
2017-10-27 12:41:00,318 21198 INFO asio_prod_01_tbm_migrated werkzeug: 127.0.0.1 - - [27/Oct/2017 12:41:00] "POST /web/action/load HTTP/1.1" 200 -
2017-10-27 12:41:01,936 21198
 WARNING asio_prod_01_tbm_migrated openerp.osv.orm.browse_record.account.invoice: Field 'invoice' does not exist in object 'browse_record(account.invoice, 4286)'
2017-10-27 12:41:01,945 21198 DEBUG asio_prod_01_tbm_migrated openerp.osv.orm.browse_record.account.invoice:   File "/home/bstanciu/workspace/odoo-7.0/openerp/service/web_services.py", line 718, in go
    (result, format) = obj.create(cr, uid, ids, datas, context)
  File "/opt/openerp/7.0/addons/report_webkit/webkit_report.py", line 332, in create
    result = self.create_source_pdf(cursor, uid, ids, data, report_xml, context)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/report/report_sxw.py", line 520, in create_source_pdf
    return self.create_single_pdf(cr, uid, ids, data, report_xml, context)
  File "/opt/openerp/7.0/addons/report_webkit/webkit_report.py", line 255, in create_single_pdf
    **parser_instance.localcontext)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7f42e49dd390", line 100, in render_body
  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/orm.py", line 505, in __getattr__
    return self[name]
  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/orm.py", line 388, in __getitem__
    self.__logger.debug(''.join(traceback.format_stack()))

2017-10-27 12:41:01,964 21198 ERROR asio_prod_01_tbm_migrated openerp.addons.report_webkit.webkit_report: 

Traceback (most recent call last):
  File "/opt/openerp/7.0/addons/report_webkit/webkit_report.py", line 255, in create_single_pdf
    **parser_instance.localcontext)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7f42e49dd390", line 180, in render_body
    <% inv = move.invoice %>
  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/orm.py", line 517, in __getattr__
    raise AttributeError(e)
AttributeError: "Field 'invoice' does not exist in object 'browse_record(account.invoice, 4286)'"

2017-10-27 12:41:01,966 21198 ERROR asio_prod_01_tbm_migrated openerp.service.web_services: Exception: (u'Rendu webkit !', u'\n\nTraceback (most recent call last):\n  File "/opt/openerp/7.0/addons/report_webkit/webkit_report.py", line 255, in create_single_pdf\n    **parser_instance.localcontext)\n  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 445, in render\n    return runtime._render(self, self.callable_, args, data)\n  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render\n    **_kwargs_for_callable(callable_, data))\n  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context\n    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)\n  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template\n    callable_(context, *args, **kwargs)\n  File "memory:0x7f42e49dd390", line 180, in render_body\n    <% inv = move.invoice %>\n  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/orm.py", line 517, in __getattr__\n    raise AttributeError(e)\nAttributeError: "Field \'invoice\' does not exist in object \'browse_record(account.invoice, 4286)\'"\n')
Traceback (most recent call last):
  File "/home/bstanciu/workspace/odoo-7.0/openerp/service/web_services.py", line 718, in go
    (result, format) = obj.create(cr, uid, ids, datas, context)
  File "/opt/openerp/7.0/addons/report_webkit/webkit_report.py", line 332, in create
    result = self.create_source_pdf(cursor, uid, ids, data, report_xml, context)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/report/report_sxw.py", line 520, in create_source_pdf
    return self.create_single_pdf(cr, uid, ids, data, report_xml, context)
  File "/opt/openerp/7.0/addons/report_webkit/webkit_report.py", line 260, in create_single_pdf
    raise except_osv(_('Webkit render!'), msg)
except_osv: (u'Rendu webkit !', u'\n\nTraceback (most recent call last):\n  File "/opt/openerp/7.0/addons/report_webkit/webkit_report.py", line 255, in create_single_pdf\n    **parser_instance.localcontext)\n  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 445, in render\n    return runtime._render(self, self.callable_, args, data)\n  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render\n    **_kwargs_for_callable(callable_, data))\n  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context\n    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)\n  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template\n    callable_(context, *args, **kwargs)\n  File "memory:0x7f42e49dd390", line 180, in render_body\n    <% inv = move.invoice %>\n  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/orm.py", line 517, in __getattr__\n    raise AttributeError(e)\nAttributeError: "Field \'invoice\' does not exist in object \'browse_record(account.invoice, 4286)\'"\n')
2017-10-27 12:41:02,214 21198 ERROR asio_prod_01_tbm_migrated openerp.netsvc: Rendu webkit !


Traceback (most recent call last):
  File "/opt/openerp/7.0/addons/report_webkit/webkit_report.py", line 255, in create_single_pdf
    **parser_instance.localcontext)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7f42e49dd390", line 180, in render_body
    <% inv = move.invoice %>
  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/orm.py", line 517, in __getattr__
    raise AttributeError(e)
AttributeError: "Field 'invoice' does not exist in object 'browse_record(account.invoice, 4286)'"
Traceback (most recent call last):
  File "/home/bstanciu/workspace/odoo-7.0/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/service/web_services.py", line 660, in dispatch
    res = fn(db, uid, *params)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/service/web_services.py", line 766, in exp_report_get
    return self._check_report(report_id)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/service/web_services.py", line 744, in _check_report
    netsvc.abort_response(exc, exc.message, 'warning', exc.traceback)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/netsvc.py", line 81, in abort_response
    raise openerp.osv.osv.except_osv(description, details)
except_osv: (u'Rendu webkit !', u'\n\nTraceback (most recent call last):\n  File "/opt/openerp/7.0/addons/report_webkit/webkit_report.py", line 255, in create_single_pdf\n    **parser_instance.localcontext)\n  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 445, in render\n    return runtime._render(self, self.callable_, args, data)\n  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 829, in _render\n    **_kwargs_for_callable(callable_, data))\n  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 864, in _render_context\n    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)\n  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 890, in _exec_template\n    callable_(context, *args, **kwargs)\n  File "memory:0x7f42e49dd390", line 180, in render_body\n    <% inv = move.invoice %>\n  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/orm.py", line 517, in __getattr__\n    raise AttributeError(e)\nAttributeError: "Field \'invoice\' does not exist in object \'browse_record(account.invoice, 4286)\'"\n')
```

**Comment by bodi000** [comment]
in l10n_ch_payment_slip/report/multi_bvr.mako:182 I noticed a call for 'objects', which retrieves 'account.invoice' not 'account.move':

`       %for move in objects:
       <% inv = move.invoice %>
       <% setLang(inv.partner_id.lang) %>
`
so 'account.invoice' obviously has no field 'invoice'.  
I see that these changes are here since 2013, maybe I miss something...

**Comment by yvaucher** [comment]
Hello,

Yes the error seems to come from:
`<% inv = move.invoice %>`

This version of the report use moves
https://github.com/OCA/l10n-switzerland/blob/7.0/l10n_ch_payment_slip/report/multi_report_webkit_html.py#L62-L65
 https://github.com/OCA/l10n-switzerland/blob/7.0/l10n_ch_payment_slip/report/multi_report_webkit_html.py#L89

Is your invoice validated ? Or are you trying to print invoice in draft ? I think this report will work only on validated invoice for which the moves were generated.

Plus, I edited your first comment to format the error to make it more readable.

**Comment by bodi000** [comment]
Hello,

Thank you for your answer and for editing!
Yes, validated invoices.

I somehow got it working by adding in report_webkit/webkit_report.py after L248:
`248        if report_xml.precise_mode:`
`249           objs = parser_instance.localcontext['objects']`

This comes actually from OCB, so thanks OCB team :-)
I am still confused, as it didn't work before with either precise mode ON or OFF.

**Comment by yvaucher** [comment]
What does the precise mode is that it will create for each invoice one pdf file, and when all pdfs are generated (in case you print multiple invoices at once) they are finally merged.

Without the precise mode, it is the standard file generation which can lead depending on the version of wkhtmltopdf to some offset after few pages.

Thanks for pointing on the solution.
