### ISSUE TITLE
Uncatched error - If no adherent number is set on partner bank

### ISSUE THREAD

**Issue by yvaucher** [OCA/l10n-switzerland#43]
When invoice.partner_bank_id.bvr_adherent_num is False

```
Traceback (most recent call last):
  File ".../server/openerp/service/web_services.py", line 712, in go
    (result, format) = obj.create(cr, uid, ids, datas, context)
  File ".../addons/report_webkit/webkit_report.py", line 332, in create
    result = self.create_source_pdf(cursor, uid, ids, data, report_xml, context)
  File ".../server/openerp/report/report_sxw.py", line 511, in create_source_pdf
    return self.create_single_pdf(cr, uid, ids, data, report_xml, context)
  File ".../addons/report_webkit/webkit_report.py", line 213, in create_single_pdf
    parser_instance.set_context(objs, data, ids, report_xml.report_type)
  File ".../l10n_ch/l10n_ch_payment_slip/report/multi_report_webkit_html.py", line 63, in set_context
    self._check(ml_ids)
  File ".../l10n_ch/l10n_ch_payment_slip/report/multi_report_webkit_html.py", line 197, in _check

  File ".../l10n_ch/l10n_ch_payment_slip/report/multi_report_webkit_html.py", line 174, in _check_invoice
    compliance = self._compile_check_bvr_add_num.match(adherent_num)
TypeError: expected string or buffer
2014-09-11 15:18:01,864 26682 ERROR test_l10n_ch openerp.netsvc: expected string or buffer
(<type 'exceptions.TypeError'>, TypeError('expected string or buffer',), <traceback object at 0x7f1efc064f80>)
Traceback (most recent call last):
  File ".../server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File ".../server/openerp/service/web_services.py", line 654, in dispatch
    res = fn(db, uid, *params)
  File ".../server/openerp/service/web_services.py", line 760, in exp_report_get
    return self._check_report(report_id)
  File ".../server/openerp/service/web_services.py", line 738, in _check_report
    netsvc.abort_response(exc, exc.message, 'warning', exc.traceback)
  File ".../server/openerp/netsvc.py", line 71, in abort_response
    raise openerp.osv.osv.except_osv(description, details)
except_osv: (u'expected string or buffer', (<type 'exceptions.TypeError'>, TypeError('expected string or buffer',), <traceback object at 0x7f1efc064f80>))
```

This would occure if l10n_ch_payment_slip is installed in an empty database. Missing dependancy ?

**Comment by nbessi** [comment]
@yvaucher no it seems more related to a missing constraint in l10n_ch bank.py this use case should not be possible.

**Comment by nbessi** [comment]
@yvaucher any news on this one
