### ISSUE TITLE
[8.0] Cannot install l10n_ch_payslip with 8ocb code

### ISSUE THREAD

**Issue by fclementic2c** [OCA/l10n-switzerland#68]
here is the traceback:

Traceback (most recent call last):
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/http.py", line 526, in dispatch
    result = self._call_function(*_self.params)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/http.py", line 282, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/http.py", line 742, in __call__
    return self.method(_args, *_kw)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/http.py", line 378, in response_wrap
    response = f(_args, *_kw)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/fclementi/openerp-instances/8ocb/parts/server/addons/web/controllers/main.py", line 940, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/modules/registry.py", line 341, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/modules/loading.py", line 162, in load_module_graph
    registry.setup_models(cr, partial=True)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/modules/registry.py", line 169, in setup_models
    model._setup_fields(cr, SUPERUSER_ID, context=context)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/api.py", line 332, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/models.py", line 2958, in _setup_fields
    field.setup(self.env)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/fields.py", line 411, in setup
    self._setup(env)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/fields.py", line 1046, in _setup
    super(Char, self)._setup(env)
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/fields.py", line 424, in _setup
    self._setup_dependency([], model, path.split('.'))
  File "/home/fclementi/openerp-instances/8ocb/parts/server/openerp/fields.py", line 560, in _setup_dependency
    fields = [model._fields[head]]
KeyError: 'code'

**Comment by nbessi** [comment]
Fixed in current PR
