### ISSUE TITLE
Payment_Slip QWEB Templates?

### ISSUE THREAD

**Issue by diezcode** [OCA/l10n-switzerland#87]
hi,
When I installed the payment_slip, I don't have any QWeb Templates of that. So I can generate a PDF but it's empty. I searched that in the Settings and i found this:
one_slip_per_page_from_invoice

This is the payment_slip temp. but it's empty with no Templates.
Why?

Thank you..

**Comment by diezcode** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/report/controllers/main.py", line 121, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 388, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/report/controllers/main.py", line 65, in report_routes
    pdf = report_obj.get_pdf(cr, uid, docids, reportname, data=options_data, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/addons/l10n_ch_payment_slip/report/payment_slip_from_invoice.py", line 50, in get_pdf
    out_format='PDF')
  File "/opt/addons/l10n_ch_payment_slip/payment_slip.py", line 642, in _draw_payment_slip
    self._draw_scan_line(draw, scan_font, (1140, 485 + a4_offset), company)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/addons/l10n_ch_payment_slip/payment_slip.py", line 552, in _draw_scan_line
    for car in self._compute_scan_line_list()[::-1]:
  File "/opt/addons/l10n_ch_payment_slip/payment_slip.py", line 212, in _compute_scan_line_list
    bank = self.move_line_id.invoice.partner_bank_id.get_account_number()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
TypeError: get_account_number() takes at least 4 arguments (4 given)
```

**Comment by nbessi** [comment]
Hello, 

The renderer does not use Qweb. 
The problem is in pure Python. Wich branch did you use ?

Regards

Nicolas

**Comment by nbessi** [comment]
My guess is that we my add an `api.model` decorator in https://github.com/OCA/l10n-switzerland/blob/8.0/l10n_ch_payment_slip/payment_slip.py#L189

**Comment by yvaucher** [comment]
@nbessi Yes it might be better to add `@api.multi` or `@api.model` (BTW it should be `@api.multi` in  case of `_compute_scan_line_list`) on each public method to stay compatible with old api.

**Comment by diezcode** [comment]
I used the 8.0 branch and with the new version from today the error is the same there

**Comment by nbessi** [comment]
@diezcode thanks can you also gives us the revision of odoo you use.

Regards

Nicolas

**Comment by diezcode** [comment]
I use debian odoo version 8.0-20150119

**Comment by diezcode** [comment]
what is now with this error : TypeError: get_account_number() takes at least 4 arguments (4 given)

**Comment by nbessi** [comment]
There was an error with the function decorator. 
This PR #105 should fix the problem
